# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # Create .env
      - name: Create secrets File
        run: |
          touch src/secrets.ts
          echo "${{ secrets.SECRETS_CONST }}" >> src/secrets.ts

      #install modules
      - name: Install node modules
        run: |
            export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            npm i

      #run build 
      - name: run build
        run: |
            npm run tsc

      - name: deploy if master
        if: github.ref == 'refs/heads/master'
        uses: AbleLincoln/push-to-sftp@v1.2
        with:
          host: us-dal-bots-02.ploxhost.com
          port: 2053
          username: ${{ secrets.PLOX_USERNAME }}
          password: ${{ secrets.PLOX_PASSWORD }}
          sourceDir: build
          targetDir: /
