# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Create .env
      - name: Create .env File
        run: |
          mkdir build && cd build
          touch .env
          echo token=${{ secrets.BOT_TOKEN }} >> .env
          echo clientId=${{ secrets.CLIENT_ID }} >> .env
          echo clientSecret=${{ secrets.CLIENT_SECRET }} >> .env
          echo starshipId=${{ secrets.STARSHIP_ID }} >> .env

      # Build bot
      - name: Cached NPM Install
        run: |
          npm ci --only=prod
          npm run build 


      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1

  deploy: 
    runs-on: ubuntu-latest
    environment: prod build
    needs: [build]
    steps:

      #Configure AWS
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: us-east-1

      #Deploy Code
      - name: Deploy Code
        id: deploy
        run: |
          aws deploy create-deployment
          --application-name starhip-bot \
          --deployment-group-name GroupAWS
          --deployment-config-name CodeDeployDefault.OneAtATime
          --github-location repository=${{ github.repository }}, commitId=${{ github.sha }}